blank_issues_enabled: true

contact_links:
  - name: GitHub Discussions
    url: https://github.com/open-ani/ani/discussions
    about: 欢迎进行相对比较正式的讨论
  - name: QQ 闲聊群 927170241
    url: http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=2EbZ0Qxe-fI_AHJLCMnSIOnqw-nfrFH5&authKey=L31zTMwfbMG0FhIgt8xNHGOFPHc531mSw2YzUVupHLRJ4L2f8xerAd%2ByNl4OigRK&noverify=0&group_code=927170241
    about: 欢迎反馈问题与闲聊
  - name: Telegram 闲聊群
    url: https://t.me/+afDaMsCSIcsyNDVk
    about: 欢迎反馈问题与闲聊
